import { AnimatePresence, motion } from 'framer-motion'
import { Activity, ArrowDownRight, ArrowUpRight, ChevronDown, CircleGauge, Lightbulb, MapPin, Minus, RadioTower, X } from 'lucide-react'
import { useState } from 'react'
import type { TwinComponent } from './model'
import { cn } from '@/lib/utils'

export function ComponentPanel({ component, onClose }: { component: TwinComponent; onClose: () => void }) {
  const Icon = component.icon
  return <motion.aside initial={{ x: '100%', opacity: 0 }} animate={{ x: 0, opacity: 1 }} exit={{ x: '100%', opacity: 0 }} transition={{ type: 'spring', damping: 29, stiffness: 320 }} className="absolute inset-y-0 right-0 z-20 flex w-full max-w-[390px] flex-col border-l bg-card/98 shadow-2xl backdrop-blur-xl">
    <div className="flex items-center justify-between border-b p-5"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></span><div><h2 className="font-semibold">{component.name}</h2><p className="mt-0.5 flex items-center gap-1.5 text-xs capitalize text-muted-foreground"><span className={cn('size-1.5 rounded-full', component.status === 'operational' ? 'bg-emerald-500' : 'bg-amber-400')} />{component.status}</p></div></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-muted" aria-label="Close details"><X className="size-5" /></button></div>
    <div className="flex-1 overflow-y-auto p-5"><div className="rounded-xl bg-gradient-to-br from-primary to-cyan-500 p-5 text-primary-foreground"><p className="text-xs font-medium opacity-80">Expected daily demand</p><div className="mt-2 flex items-end justify-between"><p className="text-3xl font-semibold">{component.expectedDemand.value}<span className="ml-1.5 text-sm font-medium opacity-80">{component.expectedDemand.unit}</span></p><span className="rounded-full bg-white/15 px-2.5 py-1 text-xs font-semibold">{component.expectedDemand.share}% total</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/20"><motion.div initial={{ width: 0 }} animate={{ width: `${component.expectedDemand.share}%` }} className="h-full rounded-full bg-white" /></div></div>
      <PanelSection title="Properties" icon={CircleGauge} defaultOpen>{component.properties.map((item) => <div key={item.label} className="flex items-center justify-between py-2 text-xs"><span className="text-muted-foreground">{item.label}</span><span className="font-semibold">{item.value}</span></div>)}</PanelSection>
      <PanelSection title="Current simulation" icon={Activity} defaultOpen><div className="grid grid-cols-2 gap-2">{component.simulation.map((item) => <div key={item.label} className="rounded-lg border bg-muted/25 p-3"><div className="flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{item.label}</span>{item.trend === 'up' ? <ArrowUpRight className="size-3 text-amber-500" /> : item.trend === 'down' ? <ArrowDownRight className="size-3 text-emerald-500" /> : <Minus className="size-3 text-muted-foreground" />}</div><p className="mt-1 text-sm font-semibold">{item.value}</p></div>)}</div></PanelSection>
      <PanelSection title="Recommendations" icon={Lightbulb} defaultOpen><ul className="space-y-2">{component.recommendations.map((item) => <li key={item} className="flex gap-2 rounded-lg bg-amber-500/[.06] p-3 text-xs leading-5"><Lightbulb className="mt-0.5 size-3.5 shrink-0 text-amber-500" />{item}</li>)}</ul></PanelSection>
      <PanelSection title="Future sensor placement" icon={RadioTower}><div className="space-y-2">{component.sensors.map((sensor) => <div key={sensor.name} className="rounded-lg border p-3"><div className="flex items-center justify-between"><p className="text-xs font-semibold">{sensor.name}</p><span className={cn('rounded-full px-2 py-0.5 text-[9px] font-bold', sensor.priority === 'High' ? 'bg-red-500/10 text-red-600' : 'bg-blue-500/10 text-blue-600')}>{sensor.priority}</span></div><p className="mt-1 flex items-center gap-1 text-[10px] text-muted-foreground"><MapPin className="size-3" />{sensor.placement}</p></div>)}</div></PanelSection>
    </div>
  </motion.aside>
}

function PanelSection({ title, icon: Icon, defaultOpen = false, children }: { title: string; icon: typeof Activity; defaultOpen?: boolean; children: React.ReactNode }) { const [open, setOpen] = useState(defaultOpen); return <section className="border-b py-1"><button onClick={() => setOpen((value) => !value)} className="flex w-full items-center gap-2 py-4 text-left"><Icon className="size-4 text-primary" /><span className="flex-1 text-xs font-semibold uppercase tracking-[.08em]">{title}</span><ChevronDown className={cn('size-4 text-muted-foreground transition-transform', open && 'rotate-180')} /></button><AnimatePresence initial={false}>{open && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden"><div className="pb-4">{children}</div></motion.div>}</AnimatePresence></section> }
